### ISSUE TITLE
Restrict ?rankup command to channel #bot-playground

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/discord-bot#26]
The ?rankup command added in recent times (thanks @Kacarott !) has gained massive popularity within the Codewars Discord server and is invoked very often. However, doing so sometimes drowns various topic channels with noise, detracting from whatever conversation was happening beforehand. As a result, a dedicated channel #bot-playground was created for the purpose of invoking this command (and possibly other future popular recreational commands), though moderators still have to constantly [remind newcomers to move over to that channel for invoking the command](https://discord.com/channels/846624424199061524/846953079710023699/935966514459332618).

Perhaps instead of manual moderation, the ?rankup command itself should only work in #bot-playground ? It would still be helpful to print an informative message in other channels though, so it doesn't give the false impression that the bot is broken or not responding.

**Comment by hobovsky** [comment]
Would it be possible to make the command work (additionally/exclusively) by DMing the bot?

**Comment by Madjosz** [comment]
Generally adding the functionality to respond to DMs is a good idea but I would not restrict the command to DM only as there is some competetive factor in having these message public visible and we are at Code**wars** at last.
Also I'd like to cite Kacarott from Discord:
> Plus I think if it was limited to just dms, we'd start getting people posting screenshots of it and stuff
