### ISSUE TITLE
Usage info for many commands hardcode PREFIX to '?'

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/discord-bot#30]
The help message for many commands hardcode the command prefix to `?` without taking `PREFIX` into account. E.g.

![Screenshot from 2022-01-27 22-57-59](https://user-images.githubusercontent.com/7777884/151384550-6b13f815-020b-4783-9c8b-0399d3e954cc.png)

**Comment by kazk** [comment]
We can get rid of `PREFIX` and always use `?`. I don't think we'll be changing it.

**Comment by DonaldKellett** [comment]
Closing since the related PR is closed.
