### ISSUE TITLE
Bridge Discord and Gitter through #legacy Discord channel

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/discord-bot#4]
While the vast majority of Codewars users have welcomed Discord with open arms, there are still a tiny percentage of users who refuse to switch to Discord for various reasons such as privacy concerns or usability, etc. While that percentage is tiny, it includes some of the best known power users on Codewars such as @Voileexperiments and @JohanWiltink . Nevertheless, without a proper bridging mechanism between Discord and legacy Gitter, the community remains split into two with no reliable method of inter-communication.

In the past few weeks, @XRFXLP has managed to relay Discord messages to Gitter and vice-versa through the use of two separate bots. He concluded that it could not be reliably achieved with a single bot due to race issues(?). This experiment demonstrates that such a bridge is feasible to implement.

The question now is: do we consider it worth the time and effort to create such a bridge? If so, perhaps we can build the Discord to Gitter relaying with this existing bot and create a separate Gitter bot for the reverse direction. What do you think?

**Comment by kazk** [comment]
I'm not interested. Discord messages are not public, but sending them to Gitter makes them public. A much more serious privacy concern than not wanting to share their Discord tag. It must be opt-in.

What's worth bridging anyway?

I was thinking Discord and GitHub Discussions to be used like this:

- Discord (sync, private): casual chats, help, ephemeral, thinking out loud
- GitHub Discussion (async, public): Q&A, discussing more concrete ideas (can be based on discussions in Discord)

We can ask for their input on GitHub, and they can start one.

---

For the split, it's not ideal, but it's not like we've split in half. The migration was definitely worth these small downsides. I'm keeping Gitter until it becomes a pain, mainly for the past messages. I wish Gitter had "archive" option, so I can archive all the rooms except for the main one.

**Comment by Voileexperiments** [comment]
> Discord messages are not public, but sending them to Gitter makes them public. A much more serious privacy concern than not wanting to share their Discord tag. It must be opt-in.

Besides not wanting to share my discord tag (my discord is for an entirely different purpose), note that discord uses a different set of redentials: Github discussions, CW (if your account's tied to github account) and gitter are all tied to a single github account. When there are two sets of separate credentials all kinds of problem arose, which is left as an exercise to the reader but I can assure that it's a lot.
