### ISSUE TITLE
Migrating to slash commands

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/discord-bot#43]
First mentioned in https://github.com/codewars/discord-bot/issues/36#issuecomment-1024850848 , there are now concrete plans to migrate our bot to use slash commands in place of ad-hoc text-based commands in order to leverage features such as autocompletion, parameter and type checking; in fact, initial support for slash commands has been added in https://github.com/codewars/discord-bot/pull/41 , though the majority of text-based commands have yet to be migrated over.

This issue aims to list and keep track of the steps required to implement an incremental, smooth migration of our bot over to slash commands, minimizing impact on users in our Discord server. Feel free to suggest changes to the list below, and / or edit the list accordingly:

1. [x] Remove support for `COMMAND_PREFIX`; update README accordingly
1. [x] Update command and message-handler templates for new project structure
1. [x] Implement `/link` command; remove `?link`
1. [x] Implement `/introduce` command; remove `?introduce`
   1. [x] \(Optional) Use new permissions mechanism to disable `/introduce` for unauthorized users
1. [x] Implement `/warn` command; remove `?warn`
1. [x] Implement `/rankup` command; remove `?rankup`
1. [x] Remove legacy command support
1. [ ] \(Optional) Make slash command argument extraction fully declarative

**Comment by kazk** [comment]
Do you want to start by removing `PREFIX` and updating README to include how to get client/guild ids? I think what you had in #37 was good.

You can also add a link to the official docs for each.

https://github.com/codewars/discord-bot/blob/7c3083ba9eaa8e07a662beabff2eeeac36a59484/src/config.ts#L24-L25

**Comment by DonaldKellett** [comment]
> Do you want to start by removing `PREFIX` and updating README to include how to get client/guild ids? I think what you had in #37 was good.

Sounds good to me. I'll open a PR shortly.

**Comment by kazk** [comment]
You can do `?link` and `?rankup` because those are for all users. Please open separate PRs.
I gave you and @Kacarott "Triage" role so you should be able to request review from him for `?rankup`.

**Comment by DonaldKellett** [comment]
Now that we've fully migrated to slash commands, maybe we should make an announcement on Discord?
