### ISSUE TITLE
/echo command freezes browser tab when echoing three backticks with format

### ISSUE THREAD

**Issue by Madjosz** [codewars/discord-bot#52]
Using the `/echo` to output three backticks ``` with optional format freezes the browser tab.

**To reproduce**
Type `/echo`, space, three backticks, tab and then click on the suggested additional `format` option.
![image](https://user-images.githubusercontent.com/28844868/152677720-48f3b2a3-bca2-4a99-ad8b-29f107f4721c.png)
This will freeze the current browser tab and keep your CPU very busy. Only option then is to close the browser tab.

**Tested with**
* Windows 10 Pro 20H2 19042.1466
* Opera Version: 83.0.4254.27
* Firefox 96.0.3 (64-Bit)

**Comment by DonaldKellett** [comment]
Can confirm:

![Screenshot from 2022-02-06 19-11-23](https://user-images.githubusercontent.com/7777884/152678096-d99da67f-c0eb-48ae-8e85-062552097b01.png)

- OS: Ubuntu 20.04
- Browser: Mozilla Firefox 96.0

**Comment by kazk** [comment]
Isn't this a Discord bug?

**Comment by DonaldKellett** [comment]
Yeah, we should probably report it to Discord.
