### ISSUE TITLE
Mention user when trainer link is posted

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/discord-bot#63]
The current message displayed when someone posts a link to the trainer is very short and concise, which minimizes the noise in the channel for all users. However, I think the bot is a _bit_ too quiet, in that 99.9% of the time, the message from the bot is just ignored with no corrective action from the OP whatsoever (or even any indication that the OP noticed the bot at all).

This means that the trainer link is still there, often much more visible than the bot's message (especially with the link preview), making it very easy for other users (e.g. me) to accidentally click on the trainer link instead of the bot's corrected link, thus effectively rendering the bot's actions completely useless.

To fix this, maybe we should make the bot's message a reply to the OP or mention the OP, just so we can at least guarantee to catch the OP's attention? That way, it doesn't increase the noise for other users, but the OP is more likely to notice their error and hopefully more likely to take corrective action as suggested by the bot.

**Comment by kazk** [comment]
I'll accept a PR to make it a reply or mention the user.
