### ISSUE TITLE
Change the command '/info user'

### ISSUE THREAD

**Issue by Djacon** [codewars/discord-bot#65]
At the moment, the command performs the simple function of showing the user name and ID on the server. I find the command not so useful. Instead, we can create a function that will show a little info about the Codewars user. 
The information includes: username, rank, honor, leaderboard position, number of katas created, number of katas completed.

The information will be displayed like this:
![info_user](https://user-images.githubusercontent.com/62030101/154839910-72acbff4-55ff-4467-b9ad-23510af6955d.png)

**Comment by Djacon** [comment]
Command is ready, if you approve my idea, I will send pull request

**Comment by kazk** [comment]
`/info` was added as an example for subcommands when migrating to (/) commands. Having Discord server info and Codewars user info under the same command feels kin of awkward.

I'm not against adding a command to get information from Codewars. I have local commits to clean up `/rankup` from last week, and we can add actual `getUser` function in the `codewars.ts` instead.

**Comment by Djacon** [comment]
Okay, I moved my `getUserInfo` function to the new `/userinfo` command. Now the command should not affect your local changes too much
