### ISSUE TITLE
CW Discord Bot failed to track number of server users for almost a month's time

### ISSUE THREAD

**Issue by ejini6969** [codewars/discord-bot#78]
Same count of user is displayed throughout this period of time!

In 13th December 2022

![image](https://user-images.githubusercontent.com/65498235/211177377-40266c1b-c265-4316-8165-69c4d368c2f9.png)

In 31st December 2022

![image](https://user-images.githubusercontent.com/65498235/211177414-5cf1e85c-0e9d-4f3a-a411-f5dfb647a885.png)

In 8th January 2023

![image](https://user-images.githubusercontent.com/65498235/211177419-a47f1c52-fb5e-4ae3-a382-42aeff85fcd5.png)

**Comment by kazk** [comment]
It's returning a cached value. When we had the bot on Heroku, this wasn't as noticeable because Heroku restarted the bot once a day.

If anyone wants to contribute, I'd start from https://discordjs.guide/miscellaneous/cache-customization.html#sweeping-caches

**Comment by kazk** [comment]
Maybe we just need to call [`guild.fetch()`](https://github.com/codewars/discord-bot/blob/c5017021634155e4c14963c06ca0c2f395b9616e/src/commands/info.ts#L25-L30) in

https://github.com/codewars/discord-bot/blob/c5017021634155e4c14963c06ca0c2f395b9616e/src/commands/info.ts#L25-L29

**Comment by kazk** [comment]
Fixed with #81.
