### ISSUE TITLE
Enable ?introduce command for power-users

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/discord-bot#9]
Currently the ?introduce command is only available to admin and mods but not power-users. Over time, this has proven to be an inconvenience as power-users may wish to tell newbies to format their code properly when asking Kata-related questions etc., but since the command is not available to them, they have to type the response manually. On the other hand, there are typically only 1 or 2 mods online at any given time and they may be too busy with other stuff to respond to newbies in a timely manner.

Since the ?introduce command is for informational purposes only, there is no reason to restrict its usage for power-users whom we expect to behave responsibly. We still do not want it to be available to any user though to prevent abuse. On the other hand, moderation tools such as ?warn should remain available only to admin and mods.

**Comment by kazk** [comment]
Yeah, I agree. PR welcomed.
